Support GROUP BY for links and tags
Currently, `[...] GROUP BY links` throws the following exception:

    beanquery.compiler.CompilationError: GROUP-BY a non-hashable type is not supported: "Column(name='links')"

because `set` is not hashable. `frozenset` is hashable, and can be used
for the `links` and `tags` which don't need to be mutable.